CREATE SCHEMA IF NOT EXISTS imagerepository;

USE imagerepository;

CREATE TABLE users (
    U_CODE SMALLINT(5) auto_increment,
    U_NAME VARCHAR(64) UNIQUE,
    U_PSWD VARCHAR(64) NOT NULL,
    PRIMARY KEY (U_CODE)
);

CREATE TABLE albums (
    A_ID SMALLINT(5) auto_increment,
    U_CODE SMALLINT(5),
    A_PRIVATE TINYINT(1),
    A_NAME VARCHAR(32),
    PRIMARY KEY(A_ID),
    FOREIGN KEY(U_CODE) REFERENCES users (U_CODE)
);

CREATE TABLE photos (
    P_ID SMALLINT(10) auto_increment,
    P_PRIVATE TINYINT(1),
    P_NAME VARCHAR(32),
    A_ID SMALLINT(5),
    U_CODE SMALLINT(5),
    PRIMARY KEY (P_ID),
    FOREIGN KEY (A_ID) REFERENCES albums (A_ID),
    FOREIGN KEY (U_CODE) REFERENCES users (U_CODE)
);